version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
      - ./backend/database.sqlite:/var/www/html/database.sqlite
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database.sqlite
    depends_on:
      - database
  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"
